timeout: '600s'

steps:
- id: 'Bazel build'
  name: 'gcr.io/bazel-public/bazel:9.0.0'
  args: ['build', '//:gowebgpu_tarball']

- id: 'Bazel cquery'
  name: 'gcr.io/bazel-public/bazel:9.0.0'
  entrypoint: '/bin/bash'
  args:
  - -ceux
  - |
    # Keep track of where the binary is located.
    echo $(bazel cquery --output=files //:gowebgpu_tarball) > /workspace/output.txt

- id: 'Docker load'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: '/bin/bash'
  args:
  - -ceux
  - |
    docker load --input $(cat /workspace/output.txt)

- id: 'Docker tag'
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gowebgpu:latest', '$LOCATION-docker.pkg.dev/$PROJECT_ID/hulkholden-dev/gowebgpu:$TAG_NAME']
images:
- '$LOCATION-docker.pkg.dev/$PROJECT_ID/hulkholden-dev/gowebgpu:$TAG_NAME'
